### ISSUE TITLE
Reference for Formulas Used in spec.m Program

### ISSUE THREAD

**Issue by yonghuier** [ilkkavir/ISspectrumMATLAB#1]
Hello,

First of all,  your excellent work help me very much. It has been very helpful in understanding the IS spectrum. I have a couple of questions regarding the calculations and output units in the program:

1. I would like to know the specific reference or theoretical basis for the formulas used in the spec.m program to calculate the theoretical spectrum. Understanding this will provide me with a clearer and more intuitive understanding of the IS spectrum.

2. I noticed a discrepancy in the units of the output between the guisdap_spec.m program and the plot ui generated. The program outputs units in m⁻³s, whereas the graphs show units in m⁻¹s. Could this be an error  that needs correction?

Thank you for your attention to these matters.

**Comment by ilkkavir** [comment]
Hi,

Thank you for the comments. 

1. I have added in the README file references to the full GUISDAP package and Vallinkoski (1989), which are probably the best available documents about how the spectrum calculation is performed in GUISDAP. If you want more details about the theory, the calculations follow the well known series of papers by Dougherty, Farley, and Swartz. Please notice that the spectrum calculation routines are directly copied from GUISDAP. 
2. The comments in guisdap_spec.m seem to be a bit inaccurate. The output is cross-section/unit volume/unit frequency, i.e. m^2/m^3/Hz, which reduces to s/m.

Hope this helps.

**Comment by yonghuier** [comment]
Thank you very much.
